version: '2'
services:

  pinklock:
    container_name: pinklock
    image: elixir:1.6
    working_dir: /app
    depends_on:
      - sentinel
    volumes:
      - ${PWD}:/app
    environment:
      - SENTINEL_HOSTS=sentinel
      - SENTINEL_NAME=panda
    command: ["/bin/bash", "-c", "apt update && apt -y install inotify-tools && mix local.hex --force && mix do deps.get, test.watch"]

  # Relies on the release candidate, not currently available as a standard image.
  redis:
    image: redis:alpine

  sentinel:
    image: s7anley/redis-sentinel-docker
    depends_on:
      - redis
    environment:
      - MASTER_NAME=panda
      - QUORUM=1
      - MASTER=redis
